# nav2_slam_only.yaml

slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # 프레임/토픽
    map_frame: map
    odom_frame: odom
    base_frame: body
    scan_topic: scan

    # TF/오도메트리
    use_odometry: true
    publish_tf: true
    provide_odom_frame: false   # <- TF 충돌 방지(필요 시만 true로)
    tf_buffer_duration: 30.0
    transform_timeout: 1.0

    # 스캔
    queue_size: 100
    max_laser_range: 20.0
    minimum_range: 1.0
    throttle_scans: 2
    resolution: 0.05


bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      allow_unknown: true

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      lookahead_dist: 0.4
      use_rotate_to_heading: false

# SLAM 중에는 global_costmap이 /map을 제대로 받는지 확인하는 용도로만 최소 구성
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: body
      update_frequency: 5.0
      publish_frequency: 2.0
      resolution: 0.05

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        # 일단 transient local로 두되, 퍼블리셔 QoS가 volatile이면 false로
        map_subscribe_transient_local: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: true
          clearing: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.0
        cost_scaling_factor: 3.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: body
      rolling_window: true
      width: 10.0
      height: 10.0
      resolution: 0.05

      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: true
          clearing: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.0
        cost_scaling_factor: 3.0
