bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astype: false
      allow_unknown: true

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 50.0
    min_x_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.05 #0.001

    goal_checker_plugins: ["general_goal_checker"] 

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      # [핵심 1] 위치: 0.35m (Lookahead가 0.4이므로 그보다 작은 최대치 설정)
      # 0.4보다 크면 오작동하지만, 0.35는 안전합니다. (기존 0.25 -> 0.35 완화)
      xy_goal_tolerance: 0.6    
      
      # [핵심 2] 각도: 0.5 rad (약 28도)
      # 각도는 Lookahead와 상관없으므로 대폭 완화했습니다. (기존 0.25 -> 0.5)
      # 이제 방향이 대충 맞아도 성공으로 뜹니다.
      yaw_goal_tolerance: 0.50   
      
      stateful: True


    
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      
      # 1. 속도 설정
      desired_linear_vel: 1.5
      min_approach_linear_velocity: 0.05
      
      # 2. Lookahead (시야)
      lookahead_time: 1.0 
      lookahead_dist: 0.4 
      max_lookahead_dist: 2.0 
      
      # 3. [회전 설정 변경] 제자리 회전 비활성화
      # [핵심] true -> false 로 변경
      # true: 각도가 안 맞으면 멈춰서 제자리 회전 후 출발 (탱크 방식)
      # false: 멈추지 않고 전진하면서 동시에 회전하여 경로 합류 (자동차 방식)
      use_rotate_to_heading: false
      
      # 아래 값들은 위 옵션이 false가 되면 자동으로 무시되지만, 
      # 나중을 위해 그대로 두셔도 상관없습니다.
      rotate_to_heading_min_angle: 0.15 
      rotate_to_heading_vel: 1.5 
      
      # 4. 코너링 자동 감속 (유지)
      # 회전하면서 출발할 때 너무 빠르면 위험하므로, 곡률에 따라 속도를 줄여주는 이 기능은 켜두는 게 좋습니다.
      use_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.5
      
      max_angular_accel: 5.0 
      max_linear_accel: 5.0 
      use_velocity_scaled_lookahead_dist: true

smoother_server:
  ros__parameters:
    use_sim_time: true
    smoother_plugins: ["SimpleSmoother"]
    SimpleSmoother:
      plugin: "nav2_smoother::SimpleSmoother"

behavior_server:
  ros__parameters:
    use_sim_time: true
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:             { plugin: "nav2_behaviors/Spin" }
    backup:           { plugin: "nav2_behaviors/BackUp" }
    drive_on_heading: { plugin: "nav2_behaviors/DriveOnHeading" }
    assisted_teleop:  { plugin: "nav2_behaviors/AssistedTeleop" }
    wait:             { plugin: "nav2_behaviors/Wait" }

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: body
      update_frequency: 10.0
      publish_frequency: 5.0
      resolution: 0.05
      track_unknown_space: true
      
      # [핵심 1] 실제 Spot 크기보다 약간 넉넉하게 설정 (안전빵)
      # Spot 실제: 길이 ~1.1m, 폭 ~0.5m -> 여유 줘서 충돌 방지
      footprint: "[ [0.6, 0.4], [0.6, -0.4], [-0.6, -0.4], [-0.6, 0.4] ]"
      
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: true
          clearing: true
          max_obstacle_height: 2.0
          
      # [핵심 2] 장애물 회피 성향 강화 (벽에서 떨어지기)
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.5      # [상향] 0.6 -> 1.5 (장애물 영향권 확대)
        cost_scaling_factor: 2.0   # [하향] 10.0 -> 2.0 (비용 감소를 완만하게 -> 벽 근처는 넓게 위험 지역으로 인식)

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: body
      update_frequency: 20.0
      publish_frequency: 10.0
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.05
      
      # 동일하게 넉넉한 Footprint 적용
      footprint: "[ [0.6, 0.4], [0.6, -0.4], [-0.6, -0.4], [-0.6, 0.4] ]"
      
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: true
          clearing: true
          max_obstacle_height: 2.0
          
      # 로컬 경로도 벽에서 떨어지도록 유도
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.5
        cost_scaling_factor: 2.0

velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 50.0
    scale_velocities: true
    max_velocity: [3.0, 0.0, 3.0] 
    min_velocity: [-1.0, 0.0, -3.0]
    accel_limit:  [3.0, 0.0, 3.0]
    decel_limit:  [3.0, 0.0, 3.0]

amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: body
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: scan
    tf_broadcast: true
    transform_tolerance: 0.2
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.05
    update_min_a: 0.05
    resample_interval: 1
    laser_model_type: "likelihood_field"
    z_hit: 0.95
    z_rand: 0.05
    sigma_hit: 0.2
    laser_likelihood_max_dist: 2.0
    set_initial_pose: false
    always_reset_initial_pose: false

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: map2.yaml